# Generated by Django 5.0.7 on 2024-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
