# Generated by Django 5.0.7 on 2024-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="win_condition",
            field=models.CharField(
                choices=[("HIGHER", "큰 숫자가 이김"), ("LOWER", "작은 숫자가 이김")],
                default="HIGHER",
                max_length=10,
            ),
        ),
    ]
