# Generated by Django 5.0.7 on 2024-07-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="game_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
