# Generated by Django 5.0.7 on 2024-07-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="game_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, default="User", max_length=20, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default="default_username", max_length=150, unique=True
            ),
            preserve_default=False,
        ),
    ]
